### ISSUE TITLE
Test issue to help view and resolve build badge for issue tracking

### ISSUE THREAD

**Issue by giddyelysium** [dellemc-symphony/root-parent#54]
- [x] I have read the [CONTRIBUTION GUIDE][contributing]

- [ ] This is a bug

- [ ] This is a feature request

- [x] This is a syntax/style fix

- [ ] This is an improvement to code quality

---

- [ ] I am having issues installing the binaries

- [ ] I am having issues building

- [ ] I am having issues with dependencies

- [x] I want to report a bug report that isn't covered here

---

I am using the following operating system:

I am using the following snapshot/release version (in the form vX.X.X) of this codebase:

I am using the following version of PostgreSQL:

I am using the following version of RabbitMQ:

I am using the following additional Symphony services and their snapshot/release versions
(in the form vX.X.X):

---

**Please provide a clear description of the issue:**  
(Note: A clear description is required in order to investigate)

_"I am having an issue with X because..."_

[contributing]: http://dellemc-symphony.readthedocs.io/en/latest/contributingtosymphony.html
[slack]: https://codecommunity.slack.com/messages/symphony
[googlegroups]: https://groups.google.com/forum/#!forum/dellemc-symphony

**Comment by giddyelysium** [comment]
Badge Added and Closing issue as resolved
